apiVersion: v1
kind: Service
metadata:
  name: {{ include "livy.fullname" . }}-http
  labels:
    {{- include "livy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "livy.selectorLabels" . | nindent 4 }}
