{{- if .Values.serviceAccounts.livy.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "livy.serviceAccountName" . }}
  labels:
    {{- include "livy.labels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.livy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
